### ISSUE TITLE
too manyindices for array in pose test

### ISSUE THREAD

**Issue by MeNinaa** [tinghuiz/SfMLearner#108]
Hi

thank you for sharing your code. I trained the model in pose mode, however now I am getting an error for testing. Can anyone help me with this please? I  downloaded the data_odometry_gray.zip file

Best regards
Maria

`python test_kitti_pose.py --test_seq 9 --dataset_dir /media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/dataset/ --output_dir  /media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/SfMLearner-master/out --ckpt_file checkpoint/model-185383
WARNING:tensorflow:From /home/maria/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
('seq_dir', '/media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/dataset/sequences/09')
('img_dir', '/media/maria/0C7ED7537ED733E4/Downloads-/inspiration_code/dataset/sequences/09/image_2')
2019-01-07 13:10:47.840369: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-07 13:10:47.913908: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-07 13:10:47.914157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.35GiB
2019-01-07 13:10:47.914169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2019-01-07 13:10:48.060579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-07 13:10:48.060605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2019-01-07 13:10:48.060609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2019-01-07 13:10:48.060770: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10017 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
('mage_seq.shape', (128, 1248))
Traceback (most recent call last):
  File "test_kitti_pose.py", line 103, in <module>
    main()
  File "test_kitti_pose.py", line 93, in main
    pred = sfm.inference(image_seq[None, :, :, :], sess, mode='pose')
IndexError: too many indices for array
`

**Comment by mariaito** [comment]
PS I renamed the folder image_1 to image_2, since there is no image_2 folder. Is that correct?
