### ISSUE TITLE
train.py InvalidArgumentError: Shape mismatch in tuple component 0. Expected [128,416,6], got [128,416,2]

### ISSUE THREAD

**Issue by gth901007** [tinghuiz/SfMLearner#112]
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    tf.app.run()
  File "/home/zyw/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 43, in main
    sfm.train(FLAGS)
  File "/home/zyw/project/Sfmlearner/SfMLearner-master/SfMLearner.py", line 262, in train
    self.save(sess, opt.checkpoint_dir, gs)
  File "/home/zyw/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/zyw/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 1005, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/zyw/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 833, in stop
    ignore_live_threads=ignore_live_threads)
  File "/home/zyw/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/zyw/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/zyw/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "/home/zyw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1205, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "/home/zyw/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape mismatch in tuple component 0. Expected [128,416,6], got [128,416,2]
How to solve this problem? Thank you!

**Comment by KerunLi** [comment]
hello, I have the same problem, have you solve it?
