### ISSUE TITLE
ValueError: cannot reshape array of size 1 into shape (3,3)

### ISSUE THREAD

**Issue by ShahZebYousafzai** [tinghuiz/SfMLearner#133]
Traceback (most recent call last):
  File "kitti_eval/eval_depth.py", line 82, in <module>
    main()
  File "kitti_eval/eval_depth.py", line 42, in main
    True)
  File "/home/shahzeb/Desktop/Shah Zeb Yousafzai/SfMLearner-master/kitti_eval/depth_evaluation_utils.py", line 175, in generate_depth_map
    velo2cam = np.hstack((velo2cam['R'].reshape(3,3), velo2cam['T'][..., np.newaxis]))
ValueError: cannot reshape array of size 1 into shape (3,3)

**Comment by ShahZebYousafzai** [comment]
I am having issues running "eval_depth.py"
