### ISSUE TITLE
test_kitti_pose.py: error: batch_unpack_image_sequence

### ISSUE THREAD

**Issue by joyyang1215** [tinghuiz/SfMLearner#21]
When I run the **test_kitti_pose.py**, I got the error for missing function **batch_unpack_image_sequence**
```
Traceback (most recent call last):
  File "test_kitti_pose.py", line 97, in <module>
    main()
  File "test_kitti_pose.py", line 62, in main
    FLAGS.seq_length)
  File "/media/cssp/Data/JoyYang/SfMLearner/SfMLearner.py", line 306, in setup_inference
    self.build_pose_test_graph()
  File "/media/cssp/Data/JoyYang/SfMLearner/SfMLearner.py", line 273, in build_pose_test_graph
    self.batch_unpack_image_sequence(
AttributeError: 'SfMLearner' object has no attribute 'batch_unpack_image_sequence'
```
But the **batch_unpack_image_sequence** is defined at **data_loader.py** for sure.
Could you tell me how to fix it?

**Comment by tinghuiz** [comment]
Should be fixed now.

**Comment by joyyang1215** [comment]
Thank you so much! I'll try it.
