### ISSUE TITLE
train.py unknown flag 'num_source'

### ISSUE THREAD

**Issue by shengsli** [tinghuiz/SfMLearner#57]
Hi @tinghuiz @ClementPinard 

- I try running this code on windows 10, and I run into an issue when I run the train command: 
```
python train.py --dataset_dir=C:\TensorFlow\SfMLearner\formatted_data\ --checkpoint_dir=C:\TensorFlow\SfMLearner\checkpoints\ --img_width=416 --img_height=128 --batch_size=4
```
- It gives the error message: 
```
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    tf.app.run()
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 41, in main
    sfm.train(FLAGS)
  File "C:\TensorFlow\SfMLearner\SfMLearner.py", line 204, in train
    opt.num_source = opt.seq_length - 1
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\flags\_flagvalues.py", line 496, in __setattr__
    return self._set_unknown_flag(name, value)
  File "C:\Users\sheng\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\flags\_flagvalues.py", line 374, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'num_source'
```

- Below is a screenshot of my command and the error message described above: 
![image](https://user-images.githubusercontent.com/29371690/37001513-ae258736-20be-11e8-9955-79b3a0c1568c.png)

- As I see it, this error occurs because there is no flag named `num_source` defined in `flags`, just as it said. Does it mean I need to add `num_source` to `flags`'s definition in train.py? If so, I am not quite clear about what `num_source` is for? 

Thank you in advance!

**Comment by tinghuiz** [comment]
It might be due to your tensorflow version that forbids adding new flags this way. But I'm not entirely sure.

**Comment by shengsli** [comment]
Hi @tinghuiz,

Thanks for your reply. If I am going to add new flags explicitly in train.py, should I initialize `num_source` and `num_scale` to NULL?

Thank you.

**Comment by tinghuiz** [comment]
Yeah, that sounds reasonable.
