### ISSUE TITLE
ValueError: 'image' must be three-dimensional.

### ISSUE THREAD

**Issue by Leaner34** [tinghuiz/SfMLearner#77]
python train.py --dataset_dir=/home/tom/SfMLearner/1/formatted / --checkpoint_dir=/home/tom/SfMLearner/1/checkpoints/ --img_width=416 --img_height=128 --batch_size=4
{'batch_size': 4,
 'beta1': 0.9,
 'checkpoint_dir': '/home/tom/SfMLearner/1/checkpoints/',
 'continue_train': False,
 'dataset_dir': '/home/tom/SfMLearner/1/formatted',
 'explain_reg_weight': 0.0,
 'img_height': 128,
 'img_width': 416,
 'init_checkpoint_file': None,
 'learning_rate': 0.0002,
 'max_steps': 200000,
 'save_latest_freq': 5000,
 'seq_length': 3,
 'smooth_weight': 0.5,
 'summary_freq': 100}
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 41, in main
    sfm.train(FLAGS)
  File "/home/tom/SfMLearner/SfMLearner.py", line 208, in train
    self.build_train_graph()
  File "/home/tom/SfMLearner/SfMLearner.py", line 25, in build_train_graph
    tgt_image, src_image_stack, intrinsics = loader.load_train_batch()
  File "/home/tom/SfMLearner/data_loader.py", line 62, in load_train_batch
    image_all, intrinsics, self.img_height, self.img_width)
  File "/home/tom/SfMLearner/data_loader.py", line 111, in data_augmentation
    im, intrinsics = random_cropping(im, intrinsics, out_h, out_w)
  File "/home/tom/SfMLearner/data_loader.py", line 103, in random_cropping
    im = tf.image.crop_to_bounding_box(im, offset_y, offset_x, out_h, out_w)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 473, in crop_to_bounding_box
    assert_ops += _Check3DImage(image, require_static=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops_impl.py", line 131, in _Check3DImage
    raise ValueError("'image' must be three-dimensional.")
ValueError: 'image' must be three-dimensional.

**Comment by liyang1991c** [comment]
Say problem. with tensorflow 1.0.0

**Comment by liyang1991c** [comment]
As @yasinalm said, raising tf version to 1.2.1 solved this problem.
